
from fishtankclient.engine.simulation.objects.CameraPositionObject import CameraPositionObject
from fishtankclient.engine.simulation.objects.FishSimObject import FishSimObject
from fishtankclient.engine.simulation.objects.SpadefishFish import SpadefishFish
from fishtankclient.engine.simulation.objects.TetraFish import TetraFish
